name: Release

on:
  push:
    branches: 
      - master
      - main

jobs:
  main:
    name: Build docs and deploy on gh-pages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v2.5
      with:
        python-version: "3.10"

    - name: Set cache variables
      id: set_variables
      run: |
        echo "::set-output name=PIP_CACHE::$(pip cache dir)"
        echo "::set-output name=PDM_CACHE::$(pdm config cache_dir)"
    
    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.set_variables.outputs.PIP_CACHE }}
          ${{ steps.set_variables.outputs.PDM_CACHE }}
        key: checks-cache

    - name: Resolve dependencies
      run: pdm lock

    - name: Install dependencies
      run: pdm install

    - name: Symlink stubs
      run: pdm run stubs
    
    - name: Build and Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        pdm run semantic-release publish -v DEBUG -D commit_author="github-actions <action@github.com>"

    - name: Build and deploy docs
      run: |
        pdm run fetch_charm
        pdm run mkdocs gh-deploy --force
